### ISSUE TITLE
Water not distributing evenly

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/FlowingLiquids#19]
Water falling into a basin tends to overflow rather than distribute evenly over the pool. With the test setup below I dumped 16 water blocks into the pool which should hold 18 blocks (6x3). I waited between dropping more water, and made sure only a single block of water is falling at the same time. However, the water overflowed instead of distributing evenly over the pool.

![image](https://user-images.githubusercontent.com/1448874/100380865-0075ca80-3018-11eb-9640-c61c944fabba.png)

I don't know whether this can (easily) be prevented. Wanted to track it anyways, though.

**Comment by 4Denthusiast** [comment]
Fixing this would require changing to quite a different style of simulation. Currently, all of the liquid flow calculations are local, depending on only a small group of nearby blocks, so it is unable to detect and even out sufficiently shallow slopes.

**Comment by skaldarnar** [comment]
Closed as **won't fix**.
