### ISSUE TITLE
Fatal error when trying to create game with flowing liquid enabled

### ISSUE THREAD

**Issue by Nhagen91** [Terasology/FlowingLiquids#8]
### What you were trying to do
Start the game with flowingliquids module enabled

### What actually happened
A fatal error occured

### How to reproduce

* Step 1: Start the game
* Step 2: Enable the below modules
* Step 3: Try to play the game

### Log details and game version
Game version:
2,250 alpha 2018-11-23T19:47:46Z

Error log:
[2018-11-25_18-19-18_2.1.1-SNAPSHOT_2250.zip](https://github.com/Terasology/FlowingLiquids/files/2613676/2018-11-25_18-19-18_2.1.1-SNAPSHOT_2250.zip)

Modules:
Core
Flowing liquids

**Comment by jellysnake** [comment]
Closing this as solved. Please reopen this if you experience the same issue again.
